{ pkgs, ... }:

let
  sync-secrets = pkgs.writeShellScriptBin "sync-secrets" ''
    #!/usr/bin/env bash
    # Generic secret sync command - fetches secrets from Bitwarden and exports them

    set -euo pipefail

    # Secret provider definitions
    PROXYMOX_ITEM="proxmox"
    RUSTFS_ITEM="rustfs"

    sync_service() {
        local service="$1"
        local item=""

        case "$service" in
            proxmox) item="$PROXYMOX_ITEM" ;;
            rustfs) item="$RUSTFS_ITEM" ;;
            *)
                echo "Error: Unknown service '$service'" >&2
                echo "Available services: proxmox rustfs" >&2
                return 1
                ;;
        esac

        echo "Syncing $service secrets from Bitwarden (item: $item)..."

        # Get secret from Bitwarden
        local SECRET_JSON
        SECRET_JSON=$("${pkgs.rbw}/bin/rbw" get "$item" --raw 2>/dev/null) || {
            echo "Error: Failed to retrieve '$item' from Bitwarden" >&2
            return 1
        }

        # Execute service-specific configuration generation
        case "$service" in
            proxmox)
                # Extract values from Bitwarden JSON
                local PROXMOX_USERNAME
                PROXMOX_USERNAME=$(echo "$SECRET_JSON" | "${pkgs.jq}/bin/jq" -r '.data.username') || return 1

                local PMX_TOKEN_SECRET
                PMX_TOKEN_SECRET=$(echo "$SECRET_JSON" | "${pkgs.jq}/bin/jq" -r '.data.password') || return 1

                local PROXMOX_VE_ENDPOINT
                PROXMOX_VE_ENDPOINT=$(echo "$SECRET_JSON" | "${pkgs.jq}/bin/jq" -r '.data.uris[0].uri') || return 1

                # Process username to extract token parts
                local PROXMOX_VE_USERNAME
                PROXMOX_VE_USERNAME=$(printf '%s' "$PROXMOX_USERNAME" | sed 's/!.*//')
                local PROXMOX_VE_TOKEN_ID
                PROXMOX_VE_TOKEN_ID=$(printf '%s' "$PROXMOX_USERNAME" | sed 's/^[^!]*!//')

                # Export variables for use in the heredoc below
                export PROXMOX_VE_USERNAME="$PROXMOX_VE_USERNAME"
                export PROXMOX_VE_TOKEN_ID="$PROXMOX_VE_TOKEN_ID"
                export PMX_TOKEN_SECRET="$PMX_TOKEN_SECRET"
                export PROXMOX_VE_API_TOKEN="$PROXMOX_VE_USERNAME!$PROXMOX_VE_TOKEN_ID=$PMX_TOKEN_SECRET"
                export PROXMOX_VE_ENDPOINT="$PROXMOX_VE_ENDPOINT"

                # Process host for PMX config
                local PMX_HOST
                PMX_HOST=$(echo "$PROXMOX_VE_ENDPOINT" | "${pkgs.gnused}/bin/sed" -E 's#^https?://##; s#:[0-9]+$##')
                export PMX_HOST="$PMX_HOST"

                # Create PMX config directory and config file
                mkdir -p "$HOME/.config/pmx"
                cat > "$HOME/.config/pmx/config.yml" <<EOCFG
current-context: homelab

contexts:
  homelab:
    host: $PMX_HOST
    port: 8006
    protocol: https
    product: pve
    auth:
      type: token
      username: $PROXMOX_VE_USERNAME
      token-id: $PROXMOX_VE_TOKEN_ID
      secret: '$PMX_TOKEN_SECRET'
    tls:
      tofu: true
EOCFG
                chmod 600 "$HOME/.config/pmx/config.yml"
                ;;

            rustfs)
                # Extract values from Bitwarden JSON
                local AWS_ACCESS_KEY_ID
                AWS_ACCESS_KEY_ID=$(echo "$SECRET_JSON" | "${pkgs.jq}/bin/jq" -r '.data.username') || return 1

                local AWS_SECRET_ACCESS_KEY
                AWS_SECRET_ACCESS_KEY=$(echo "$SECRET_JSON" | "${pkgs.jq}/bin/jq" -r '.data.password') || return 1

                local AWS_ENDPOINT_URL
                AWS_ENDPOINT_URL=$(echo "$SECRET_JSON" | "${pkgs.jq}/bin/jq" -r '.data.uris[0].uri') || return 1

                local AWS_REGION
                AWS_REGION=$(echo "$SECRET_JSON" | "${pkgs.jq}/bin/jq" -r '.data.region // "us-east-1"') || return 1

                # Export variables for use in the heredoc below
                export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
                export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
                export AWS_ENDPOINT_URL="$AWS_ENDPOINT_URL"
                export AWS_REGION="$AWS_REGION"
                ;;

            *)
                echo "Error: No handler for service '$service'" >&2
                return 1
                ;;
        esac

        # Create shell-specific export files in ~/.config/zsh
        local EXPORT_DIR="$HOME/.config/zsh"
        mkdir -p "$EXPORT_DIR"
        
        case "$service" in
            proxmox)
                cat > "$EXPORT_DIR/proxmox.zsh" <<EOF
# Auto-generated by sync-secrets - DO NOT EDIT MANUALLY
export PROXMOX_VE_USERNAME="$PROXMOX_VE_USERNAME"
export PROXMOX_VE_TOKEN_ID="$PROXMOX_VE_TOKEN_ID"
export PMX_TOKEN_SECRET="$PMX_TOKEN_SECRET"
export PROXMOX_VE_API_TOKEN="$PROXMOX_VE_USERNAME!$PROXMOX_VE_TOKEN_ID=$PMX_TOKEN_SECRET"
export PROXMOX_VE_ENDPOINT="$PROXMOX_VE_ENDPOINT"
export PMX_HOST="$PMX_HOST"
EOF
                chmod 600 "$EXPORT_DIR/proxmox.zsh"
                ;;
            rustfs)
                cat > "$EXPORT_DIR/rustfs.zsh" <<EOF
# Auto-generated by sync-secrets - DO NOT EDIT MANUALLY
export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
export AWS_ENDPOINT_URL="$AWS_ENDPOINT_URL"
export AWS_REGION="$AWS_REGION"
EOF
                chmod 600 "$EXPORT_DIR/rustfs.zsh"
                ;;
        esac

        echo "$service secrets synced successfully!"
        echo "Shell export files created in $EXPORT_DIR/"
    }

    # Main entry point
    if [ $# -eq 0 ]; then
        # If no arguments provided, sync all services
        echo "No services specified, syncing all services..."
        sync_service "proxmox" || true
        sync_service "rustfs" || true
    else
        # Sync specified services
        for service in "$@"; do
            sync_service "$service" || exit 1
        done
    fi
  '';
in
{
  home.packages = [
    sync-secrets
  ];
}
